<?php
/**
 * @var \RookieSoft\CustomerTags\Block\Adminhtml\GuestCustomer\View $block
 */
?>
<section class="admin__page-section">

    <div id="order_tags" class="entry-edit form-inline">
        <div class="rookiesoft__page-section-title">
            <h1><?php echo $this->getUrl("customertags/sales/save") ?></h1>
            <h1><?php echo $block->getSubmitUrl() ?></h1>
            <span class="title"><?= $block->escapeHtml(__('Tags Form')) ?></span>
        </div>
        <div class="admin__fieldset-wrapper-content _hide">
            <form class="form" id="tag_form" method="post">
                <fieldset class="admin__fieldset">
                    <div class="admin__field" data-bind="css: $data.additionalClasses, attr: {'data-index': index}, visible: visible" data-index="tagToCustomer">
                        <div class="admin__field-label" data-bind="visible: $data.labelVisible">
                            <label>
                                <span>Select Tag</span>
                            </label>
                        </div>
                    <div class="admin__field-control" id="dropdown">
                        <div class="admin__action-multiselect-wrap action-select-wrap _active" tabindex="0">
                            <div class="action-select admin__action-multiselect _active">
                                <div class="admin__action-multiselect-text">Select...</div>
                                <?php foreach($block->getSelectedTags() as $selectedTag){ ?>
                                    <span class="admin__action-multiselect-crumb selected-tag">
                                        <span class='<?=$selectedTag->getCode()?>'><?= $selectedTag->getLabel()?></span>
                                        <button class="action-close" type="button">
                                            <span class="action-close-text">Close</span>
                                        </button>
                                        <input name="tag[]" type="hidden" value='<?=$selectedTag->getCode()?>'>
                                    </span>
                                <?php } ?>
                            </div>
                            <div class="action-menu _active" id="dropdown-content" style="display: none;">
                                <div class="admin__action-multiselect-search-wrap">
                                    <input class="admin__control-text admin__action-multiselect-search" data-role="advanced-select-text" type="text" autofocus="true" id="search">
                                    <label class="admin__action-multiselect-search-label" >
                                    </label>
                                    <div
                                    class="admin__action-multiselect-search-count" style="display: none;">1 options</div>
                                </div>
                                <ul class="admin__action-multiselect-menu-inner _root">
                                    <?php foreach($block->tagsOptions() as $tag){ ?>
                                        <li class="admin__action-multiselect-menu-inner-item _root" >
                                            <div class="action-menu-item _last">
                                                <label class="admin__action-multiselect-label">
                                                    <span class="tag"><?= $tag->getLabel() ?></span>
                                                    <input type="hidden" value="<?=$tag->getCode()?>">
                                                </label>
                                            </div>
                                        </li>
                                    <?php } ?>
                                </ul>
                                <div class="admin__action-multiselect-actions-wrap">
                                    <button class="action-default" data-action="close-advanced-select" type="button" data-bind="click: outerClick">
                                        <span data-bind="i18n: closeBtnLabel">Done</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                    <input class="admin__control-text" type="hidden"
                            name="order_id" maxlength="255" value="<?= $block->escapeHtml($block->getOrderId()) ?>">
                    <input type="submit" value="Save" class="save">
                </fieldset>
            </form>
        </div>
    </div>
</section>
<script type="text/javascript">
require([
    'jquery',
    'mage/template',
    'jquery/ui',
    'mage/translate'
],function($) {
    //$('body').loader("show");
//$(document).ready(function() {
    $('section').trigger('processStart');
    $('admin__control-text data-grid-search-control').remove();
    if ($('.admin__action-multiselect-crumb').length > 0) {
        $('.admin__action-multiselect-text').hide();
    }else{
        $('.admin__action-multiselect-text').show();
    }
    $('#dropdown').click(function() {
        $('#dropdown-content').toggle()
        if ($('.admin__action-multiselect-crumb').length > 0) {
            $('.admin__action-multiselect-text').hide();
        }else{
            $('.admin__action-multiselect-text').show();
        }
    });
    $('.action-menu-item').hover(function(){
        $(this).addClass('_hover');
    },
    function(){
        $(this).removeClass('_hover');
    }
    );
    $('#search').hover(function(){
        $(this).focus();
    });
    $('.action-menu-item').click(function(){
        $('#dropdown-content').hide()
        var text = $(this).children().text();
        var value = $('input', $(this)).val();
            $('.admin__action-multiselect-text')
            .after('<span class="admin__action-multiselect-crumb"><span class='+value+'>'+text+'</span><button class="action-close" type="button"><span class="action-close-text">Close</span></button><input name="tag[]" type="hidden" value='+value+'></span>');
        if($('.'+value).length != 1){
            $('.'+value).parent().remove();
        }
        $('.action-close').click(function(){
            $(this).parent().remove();
        });

    });
    $('.action-close').click(function(){
        $(this).parent().remove();
    });
    $menu = $('#dropdown-content');

    $(document).mouseup(e => {
       if (!$menu.is(e.target) // if the target of the click isn't the container...
       && $menu.has(e.target).length === 0) // ... nor a descendant of the container
        {
            $menu.hide();
        }
    });
    $(".admin__fieldset-wrapper-content .save").click(function(){
        var orderIdValue = $("input[name='order_id']").val();
        var tagValue = $("input[name='tag[]'").map(function(){
            return $(this).val();
        }).get();
        console.log(tagValue);
        var url = "<?php echo $this->getUrl("customertags/sales/save") ?>";
        $.ajax({
            url: url,
            type: "GET",
            data: {orderId:orderIdValue, tagCode:tagValue},
            dataType: "json",
            showLoader: true,
            context: $('#order_tags'),
            cache: true,
            success: function(response){
                console.log("XXXXXXXXXXXXXXXXXXXXXXXXXXX");
            }
        });
        return false;
    });

    $('.admin__action-multiselect-search').on('keyup',function(){
        var input, filter, a, i;
        input = document.getElementById("search");
        filter = input.value.toUpperCase();
        div = document.getElementById("dropdown-content");
        a = div.getElementsByClassName("admin__action-multiselect-menu-inner-item");
        //$("admin__action-multiselect-search-count").show()
        for (i = 0; i < a.length; i++) {
            txtValue = a[i].textContent || a[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "";
                $("admin__action-multiselect-search-count").show()
            } else {
                a[i].style.display = "none";
            }
        }
    });
});


</script>